In [16]:
from scipy import integrate
from itertools import product
import matplotlib.pyplot as plt
import matplotlib as mpl
from cycler import cycler

In [14]:
import numpy as np
npz = np.load('part1a.npz')
lst = npz.files


for item in lst:
  print(item)
  print(npz[item])

N = npz ['N']
SVC_0_pmf = npz['Svc_0_pmf']
Lc = npz['Lc'] 
I_v= npz['Ic_0']
gamma = npz['gamma']


R = np.zeros(1)
R[0] = 0
S_v = np.multiply(SVC_0_pmf, N)
S_v = S_v.flatten()
Z = np.zeros(21)
I = np.sum(I_v)
S_v_I_v_R = np.concatenate((S_v,I_v, R ))

N
100000.0
Svc_0_pmf
[[0.10953309 0.03300776 0.08179044 0.11593994]
 [0.03089752 0.08511994 0.04528764 0.05718283]
 [0.07471465 0.02495643 0.10236599 0.04256696]
 [0.01605863 0.08109608 0.09158212 0.00789999]]
Lc
[0.3 0.4 0.7 1. ]
Ic_0
[47 90 51 65]
gamma
0.07142857142857142


### Relavent information 
-  Lc is the viral load for a person in the comorbidity compartment c.
- γ is the reciprocal of the typical time until an infected person recovers (or succumbs)
- The known model parameters are the 
    - **initial susceptible populations** in each compartment in each leaf node, 
    - the **initial infected populations Ic** in each leaf node, Lc values and γ
    - assume that **initial recovered populations are zero** (i.e. R = 0) and that initially Sv,c >> Ic for all v and c, therefore N = sum S sub 0 v and c 

- What is not known 
    - Bvc 

- SVC PMF 
    - Probability Distribution is a statistical function which links or lists all the possible outcomes a random variable can take, in any random process, with its corresponding probability of occurrence.

NOTES
    
    I sum = all elements of Iv 

     S[0] will be S_{0,0}
     S[1] will represent S_{0,1}
      S[4] will represent S_{1,0}

     Svc_0_pmf array gives the joint probability distribution over v and c
for example Svc_0_pmf[0,1] holds the value of PMF of S(v=0, c=1)
     s is of size 16 
     S+I+R = 0?
    S = 16, Z should be of size 21 
     second argument corresponds to each variable used in the equation
     first 16 indicies belong to 
     was unsure how to represent that  dIc/dt was composed of dSvc/dt this is what I came up with but I'm still unsure 
    what is being returnd by G is the first right hand values 
     probably due that in a four loop 
    hold all right hand side that compute in some sort of an array 
     do the same for I 
     for R. compute dr/ dt concationate all and have array of 21 vlaues 
    gives array to be returned same size as Z
     I=I[0]+I[1]+..+I[3] 
     I vector vs I sum 

In [18]:

color = plt.cm.jet(np.linspace(0.1,0.9,10))
mpl.rcParams['axes.prop_cycle'] = cycler('color', color)
#### color settings


N = 10000
# planning on creating a for loop to cycle through 
B = .5
dS_dI_dr = np.zeros(21)

def lotka_volterra(t, Z, B, I, gamma, N, S_v, I_v):
    S_v,I_v,R=Z[0:16],Z[16:20],Z[20]
 
    S_dt_arr = np.zeros(16)
    for i in range (0,15):
        S_dt_arr[i] = -((B * S_v[i] * I )/N)

    I_dt_arr = np.zeros(4)
    for i in range (0,3):
        I_dt_arr[i] = (G- (gamma*I_v))


    R_dt = np.zeros(1)
    R_dt[0] = (gamma * I) 

    dS_dI_dr = np.concatenate((S_dt_arr,I_dt_arr,R_dt))

    return dS_dI_dr

# concatenaded array of solved DE, don't use any other place 
# once this function is defined the ode solver will use this equation, then solve me 



t=np.linspace(0,120,120)
(S0 , I0 , R0)= (S_v, I_v, R)
# all values computed by multiplying pmf with N, I = I , R = 0
# inital consiitons of zise 21 concatenate all inital feed into here 
initial_conditions = S_v_I_v_R

fig=plt.figure()
for initial_condition in initial_conditions:

    
    soln_obj=integrate.solve_ivp(lotka_volterra, (t[0],t[-1]), initial_condition, \
                            args=(B, I, gamma, N), dense_output=True)
        # sol obj. solve fed t, will give all the time series once .solve is used will give the time series of each of the steps                     
    plot_handles.append(plt.plot(soln_obj.sol(t)[0],soln_obj.sol(t)[1], linewidth=1)[0])

plt.annotate(f"", xy=(0.5, 0.9), \
            xycoords='axes fraction', size=9, ha='center', \
            va='center', bbox=dict(boxstyle='round', fc='w'))
plt.xlabel("x")
plt.ylabel("y").set_rotation(0)
plt.gca().set_aspect('equal')
plt.tight_layout()
plt.show()


ValueError: `y0` must be 1-dimensional.